---
- name: "Setup pfsense firewalls"
  hosts: "pfsense"
  roles:
    - example_firewall

  vars:
    net:
      one:
        wanip: 192.2.0.8
        wangw: 192.2.0.9
      two:
        wanip: 192.2.0.10
        wangw: 192.2.0.11
