---

- name: "Setup pfsense firewalls"
  hosts: "pfsense"
  roles:
    - example_firewall

  vars:
    net:
      one:
        wan:
          ip: 208.53.31.117
          gw: 208.53.31.113
          vip: 208.53.51.116
        lan:
          ip: 10.16.0.2
          gw: ''
          vip: 10.16.0.1
      two:
        wan:
          ip: 208.53.31.118
          gw: 208.53.31.113
          vip: 208.53.31.116
        lan:
          ip: 10.16.0.3
          gw: ''
          vip: 10.16.0.1

