---

- hosts: pfsense

  vars:
    sync_interface: opt2
    sync_ip:  10.4.4.4
    password: pfsense

  tasks:
   - name: pfSense High Availability Sync
     pfsense_config:
       hasync: 
         pfsyncenabled: "on"
         synchronizeusers: "on"
         synchronizeauthservers: "on"
         synchronizecerts: "on"
         synchronizerules: "on"
         synchronizeschedules: "on"
         synchronizealiases: "on"
         synchronizenat: "on"
         synchronizelb: "on"
         synchronizevirtualip: "on"
         synchronizetrafficshaper: "on"
         synchronizetrafficshaperlimiter: "on"
         synchronizednsforwarder: "on"
         pfsyncpeerip: "{{ sync_ip }}"
         pfsyncinterface: "{{ sync_interface }}"
         synchronizetoip: "{{ sync_ip }}"
         username: admin
         password: "{{ password }}"
