---

- name: Setup Temporary DNS
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ item }}"
    insertbefore: BOF
  with_items:
    - 8.8.8.8
    - 1.1.1.1

- name: Setup WAN Interface
  pfsense_interfaces:
    name: wan
    descr: OUTSIDE
    ipaddr: "{{ net[machine_id].wan.ip }}"
    gateway: "{{ net[machine_id].wan.gw }}"
    subnet: 31

- name: Setup LAN Interface
  pfsense_interfaces:
    name: lan
    descr: INSIDE
    # IP address already set manually, we're already using it to config this firewall

- name: Apply Settings
  pfsense_apply:
    services:
      - interfaces

- name: Set Password & SSH Keys
  pfsense_password:
    username: admin
    password: pfsense
    authorizedkeys: "{{ lookup('file', '~/.ssh/authorized_keys' ) | b64encode }}"

- name: LAN Virtual IP
  pfsense_virtualip:
    mode: ipalias
    interface: lo0
    descr: "WAN"
    type: single
    subnet_bits: 32
    subnet: "{{ net[machine_id].lan.vip }}"
    state: present
  check_mode: yes

- name: WAN Virtual IP
  pfsense_virtualip:
    mode: ipalias
    interface: lo0
    descr: "WAN"
    type: single
    subnet_bits: 32
    subnet: "{{ net[machine_id].wan.vip }}"
    state: present
  check_mode: yes

- name: Create Staff Group
  pfsense_group:
    name: Staff
    description: Staff Users
    priv:
      - "page-all"

- name: Configuration
  pfsense_config:
    safe_mode: no  # Some items don't exist yet in pristine untouched firewall
    system:
      hostname: "{{ inventory_hostname }}"
      domain: "{{ domain }}"
      timezone: America/Denver
      timeservers: 0.pfsense.pool.ntp.org
      dnsserver:
        - 1.1.1.1
        - 8.8.8.8
      dnslocalhost: ""
    nat:
      outbound:
        mode: hybrid

- name: Firewall Aliases
  pfsense_aliases:
    name: "{{ item.name }}"
    descr: "{{ item.descr | default('') }}"
    type: "{{ item.type }}"
    address: "{{ item.address }}"
    detail: "{{ item.detail | default('') }}"
  with_items: "{{ fw_aliases }}"

- name: Firewall Filter Rules
  pfsense_filter_rules:
    state: "{{ item.state | default('present') }}"
    tracker: "{{ item.tracker }}"
    type: "{{ item.type | default('pass') }}"
    interface: "{{ item.interface | default('lan') }}"
    ipprotocol: "{{ item.ipprototcol | default('inet') }}"
    direction: "{{ item.direction | default('any') }}"
    floating: "{{ item.floating | default(omit) }}"
    statetype: "{{ item.statetype | default('keep state') }}"
    protocol: "{{ item.protocol | default(omit) }}"
    source: "{{ item.source | default(dict(any='')) }}"
    destination: "{{ item.destination | default(dict(any='')) }}"
  with_items: "{{ fw_filter }}"

